= API Documentation of the Plant Pod backend

NOTE: All request bodies have to be provided as JSON formatted string.

== Submit sensor data (arduino)

=== POST `/sensors`
Description::
submit sensor data from the arduino to the backend
Request params:: none
Query params:: none
Request body::
* id [GUID]
* temperature [decimal]
* humidity [decimal]
* moisture [decimal]
* ph [decimal]

Example request::
[source, json]
{
    "id": "196db225-e5ef-4636-b967-c214a0ddb73f",
    "temperature": 14.3,
    "humidity" = 40.3,
    "moisture" = 53.7,
    "ph" = 7.5
}

Response::
200 (Ok)

Errors::
400 (Bad Request) - when sensor id is null, invalid or unknown
500 (Internal server error)

== Get sensor data (frontend)

=== GET `/livedata`
Description::
get livedata from all sensors
Request params:: none
Query params:: none

Example response::
[source, json]
[
    {
        "id": "196db225-e5ef-4636-b967-c214a0ddb73f",
        "temperature": 14.3,
        "humidity" = 40.3,
        "moisture" = 53.7,
        "ph" = 7.5
    },
    [...]
]

Response::
200 (Ok)

Errors::
500 (Internal server error)

=== GET `/livedata/{id}`
Description::
get livedata for one sensor
Request params::
* id [Guid]
Query params:: none

Example response::
[source, json]
{
    "id": "196db225-e5ef-4636-b967-c214a0ddb73f",
    "temperature": 14.3,
    "humidity" = 40.3,
    "moisture" = 53.7,
    "ph" = 7.5
}

Response::
200 (Ok)

Errors::
400 (Bad Request) - when sensor id is null, invalid or unknown
500 (Internal server error)

== Get plant data (frontend)

=== GET `/plants`
Description::
get all plant data
Request params:: none
Query params:: none

Example response::
[source, json]
[
    {
        "id": "4eeb3e42-c47e-4930-9464-ce81c74502df",
        "longName": "plant long name",
        "shortName": "plant short name",
        "description": "just some random plant",
        "care": "don't let it dry out",
        "minTemperature": 12.40,
        "maxTemperature": 35.70,
        "minph": 6.50,
        "maxph": 9.10,
        "minHumidity": 13.20,
        "maxHumidity": 30.40,
        "moisture": "Dry",
        "image": "source path"
    },
    [...]
]

Response::
200 (Ok)

Errors::
500 (Internal server error)

=== GET `/plants/{id}`
Description::
get data for one plant
Request params::
* id [Guid]
Query params:: none

Example response::
[source, json]
{
    "id": "4eeb3e42-c47e-4930-9464-ce81c74502df",
    "longName": "plant long name",
    "shortName": "plant short name",
    "description": "just some random plant",
    "care": "don't let it dry out",
    "minTemperature": 12.40,
    "maxTemperature": 35.70,
    "minph": 6.50,
    "maxph": 9.10,
    "minHumidity": 13.20,
    "maxHumidity": 30.40,
    "moisture": "Dry",
    "image": "source path"
}

Response::
200 (Ok)

Errors::
400 (Bad Request) - when sensor id is null, invalid or unknown
500 (Internal server error)
