// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantPodService.Model;

namespace PlantPodService.Migrations
{
    [DbContext(typeof(PlantPodServiceDbContext))]
    partial class PlantPodServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlantPodService.Model.PlantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Care")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Image")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LongName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("MaxHumidity")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("MaxTemperature")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("Maxph")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("MinHumidity")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("MinTemperature")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("Minph")
                        .HasColumnType("decimal(16,2)");

                    b.Property<int>("Moisture")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
